# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aSmnHLUay0Km9Tj8JUoHRGxT5rkT-qoL
"""

import pandas as pd

df = pd.read_csv('/content/data.csv')

print(df.head(10))

#Mean
x = df["batsman_runs"].mean()
print(int(x))
#df["batsman_runs"].fillna(x, inplace = True)

#Median
x = df["batsman_runs"].median()
print(x)
#df["batsman_runs"].fillna(x, inplace = True)

#Mode
x = df["batsman_runs"].mode()[0]
print(x)
#df["batsman_runs"].fillna(x, inplace = True)